name: backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5
          
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version:  v1.53.3
          working-directory: ./backend/
          
    - name: Build
      working-directory: backend
      run: go build -v ./...

    - name: Test
      working-directory: backend
      run: go test -v ./...
      
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        working-directory: ./backend/
      
    - name: Run gofmt
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: ./
        gofmt-flags: -l -d  
        working-directory: ./backend/
