name: backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
          
    - name: Install linter
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ./backend/
        
    - name: Lint code
      working-directory: ./backend/
      run: golangci-lint run 
      
    - name: Build
      working-directory: backend
      run: go build -v ./...

    - name: Test
      working-directory: backend
      run: go test -v ./...
      
    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        working-directory: ./backend/
      
    - name: Run gofmt
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: ./
        gofmt-flags: -l -d  
        working-directory: ./backend/
