name: Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Lint Code 
      working-directory: frontend
      run: npx eslint --ext .js,.vue --fix src
      
    - name: Clean Install
      working-directory: frontend
      run: npm ci
      
    - name: Build
      working-directory: frontend  
      run: npm run build --if-present
