name: Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        working-directory: frontend
        node-version: '20.x'
        
    - name: Install Ddependencies
      working-directory: frontend
      run: npm install
      
    - name: Lint Code 
      working-directory: ./frontend/
      run: npx eslint --ext .js,.vue --fix src
      
    - name: Clean Install
      working-directory: ./frontend/
      run: npm ci
      
    - name: Build
      working-directory: ./frontend/  
      run: npm run build --if-present
